### ISSUE TITLE
os question

### ISSUE THREAD

**Issue by Omenranr** [Arpitrf/Hand-Gesture-Recognition#2]
Hello you did a great work thank you for sharing it, I have a question can I run the project on mac os x ?

**Comment by ankurdengla** [comment]
Hi @Omenranr! 
Yes, you can run the project on macOS provided you have all the pre-requisites as mentioned in the readme.

**Comment by Omenranr** [comment]
Ok, I have another question. Is it possible to use client.py or the pretrained models without naoqi ? I'm trying to test the pretrained weights but I have a probleme in loading them I get this error
![image](https://user-images.githubusercontent.com/5864369/58372307-b3dd9a80-7f1b-11e9-9503-a8aec301cb4f.png)

**Comment by Omenranr** [comment]
I continued until I did the prediction and it seems that it's working I had an output:
tensor([[-4.0156, 10.1121,  6.1371, -4.7847, -2.1117, -2.8172, -5.8223,  2.9443]])
the prediction I guess is the max(10.1121 index 1 sliding fingers left) the sample images I used are indeed sliding fingers left

So my main question now is if I can use client.py without naoqi (just pyqt4)

**Comment by ankurdengla** [comment]
@Omenranr Yes, you can use the model directly without naoqi if your use case does not involve communicating with a Nao robot. Although, the code as it is will give some errors so you'll have to amend the code accordingly.

**Comment by Omenranr** [comment]
Ok thank you for your help !
